### ISSUE TITLE
problems in critic model

### ISSUE THREAD

**Issue by Juanting-Xu** [Zyq-scut/RLTF#1]
Hello, I noticed that you have trained a four classification model (Critic).
what are the accuracy, recall, f1_score of the classification model in APPS testset. how to determine whether the critic model is ready？

**Comment by Zyq-scut** [comment]
Hi @Juanting-Xu. For CodeT5, we utilized the provided [checkpoint](https://console.cloud.google.com/storage/browser/sfr-coderl-research/codet5_finetuned_critic;tab=objects?prefix=&forceOnObjectsSortingFiltering=false) from [CodeRL](https://github.com/salesforce/CodeRL). For CodeGen, we follow the script from [CodeRL](https://github.com/salesforce/CodeRL) to train a critic and selected the final checkpoint as the model. Although we did not compute the matrix in the testset, we noticed that the accuracy reached 90% early in the training process, leading us to believe that the final checkpoint may be overfitting.
