### ISSUE TITLE
Is this method can be transferred to general LLM?

### ISSUE THREAD

**Issue by SupritYoung** [Zyq-scut/RLTF#2]
I notice that your work only focus on code LLM, I wanna to use your method in general LLM to fix some factual error in model's response. Sincerely ask you for advice.

**Comment by Zyq-scut** [comment]
I think the key is to accurately classify and locate the factual errors and give LLM feedback. For code LLM, it is easy to do with compiler. Hope this help. : )

**Comment by SupritYoung** [comment]
Thank you so much ! We're trying to solve this point, it's hopeful to realize. But I also have a question: If the location is not clear (natural language in reality is non-linear), but you know what information is wrong, is there a recommended solution?

**Comment by SupritYoung** [comment]
BTW, what exactly does "the amplitude fluctuation in fine-grained feedback caused by variable values of S and E" mean in the paper, Is $L_{adaptive}$introduced to alleviate this problem?

**Comment by Zyq-scut** [comment]
> Thank you so much ! We're trying to solve this point, it's hopeful to realize. But I also have a question: If the location is not clear (natural language in reality is non-linear), but you know what information is wrong, is there a recommended solution?

If you are not sure where the location of wrong information is, you can try to use coarse-grained feedback only.

**Comment by Zyq-scut** [comment]
> BTW, what exactly does "the amplitude fluctuation in fine-grained feedback caused by variable values of S and E" mean in the paper, Is $L_{adaptive}$introduced to alleviate this problem?

The loss is averaged over tokens. Assuming that the total token length is $T$ and the small code length is $E-S$, then the value of $L_{fine}$ is about $R*(E-S)/T$ after averaging. If $E-S/T$ is particularly small, this will make fine-grained feedback ineffective during training, so we introduce $\alpha$ to adaptively amplify it.

**Comment by SupritYoung** [comment]
Thank you so much !
