### ISSUE TITLE
Could I get the final version of the data that contains 'pass_ratio', 'error_line', 'reward_type'

### ISSUE THREAD

**Issue by ZJXNEFU** [Zyq-scut/RLTF#3]
For the data in this repo, there are no 'pass_ratio', 'error_line', 'reward_type' in gen_solutions_critic_scores.pkl

**Comment by ZJXNEFU** [comment]
And how to get the error_hidden_states

**Comment by liujiate** [comment]
We have updated the 'gen_solutions_critic_scores_0.pkl' to include the 'pass_ratio', 'error_line', and 'reward_type' attributes. For the mentioned properties, you can refer to the 'generate_online.py', which is responsible for generating program samples online.
