### ISSUE TITLE
Is there any plan to add RLTF to the current state-of-the-art code model? Like starcoder or other LLM?

### ISSUE THREAD

**Issue by PoseidomWong** [Zyq-scut/RLTF#4]
Is there any plan to add RLTF to the current state-of-the-art code model? Like starcoder or other LLM?

**Comment by Zyq-scut** [comment]
Sorry, we have no plans to do these currently. You need to implement it by yourself. Take starcoder as an example, you need to rewrite the forward function of the [GPTBigCodeForCausalLM](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L783) class to adapt to the loss required for RL training. You can refer to our modified [CodeGenForCausalLMclass](https://github.com/Zyq-scut/RLTF/blob/main/trainers/modeling_codegen.py#L679) and the original [CodeGenForCausalLMclass](https://github.com/huggingface/transformers/blob/main/src/transformers/models/codegen/modeling_codegen.py#L654). When you have finished these, you need to replace the model in [train_codegen.py](https://github.com/Zyq-scut/RLTF/blob/main/train_codegen.py#L54) and [train_codegen_online_v1.py](https://github.com/Zyq-scut/RLTF/blob/main/train_codegen_online_v1.py#L55) to perform RLTF training.

**Comment by PoseidomWong** [comment]
Do I need to change the data format? The chat version of starcoder is in instruction/output format and your is QUESTION/ANSWER format

**Comment by Zyq-scut** [comment]
I think both are fine. Just use same format for training and generating.

**Comment by PoseidomWong** [comment]
Thanks for your reply!
