### ISSUE TITLE
请问利用buffer中生成的内容进行RL的代码是哪一部分呀

### ISSUE THREAD

**Issue by Ptah4E00** [Zyq-scut/RLTF#5]
孩子要看哭了，救救孩子

**Comment by Zyq-scut** [comment]
In the training loop, we obtain the training data from the [enumerate_epoch_iterator](https://github.com/Zyq-scut/RLTF/blob/main/trainers/trainer_rl_online_v1.py#L1310), and we update the memory buffer using the [update_sample](https://github.com/Zyq-scut/RLTF/blob/main/trainers/trainer_rl_online_v1.py#L1441) method every 50 steps. More specifically, the most recently generated sample is added to the data pool, while the oldest one is removed. This ensures that the dataloader always reads the latest generated data. You can find the relevant code [here](https://github.com/Zyq-scut/RLTF/blob/main/datasets/apps_dataset_online_v1.py#L297).
